local opt = vim.opt

opt.clipboard = "unnamedplus" -- allows neovim to access the system clipboard
-- opt.cmdheight = 2 -- more space in the neovim command line for displaying messages
-- opt.conceallevel = 0 -- so that `` is visible in markdown files
-- opt.fileencoding = "utf-8" -- the encoding written to a file
-- opt.encoding="utf-8"
-- opt.hlsearch = true -- highlight all matches on previous search pattern
-- opt.ignorecase = true -- ignore case in search patterns
opt.mouse = "a" -- allow the mouse to be used in neovim
opt.showmode = false -- we don't need to see things like -- INSERT -- anymore
-- opt.showtabline = 2 -- always show tabs
-- opt.smartcase = true -- smart case
-- opt.smartindent = true -- make indenting smarter again
opt.splitbelow = true -- force all horizontal splits to go below current window
opt.splitright = true -- force all vertical splits to go to the right of current window
-- opt.swapfile = false -- creates a swapfile
opt.termguicolors = true -- set term gui colors (most terminals support this)
-- opt.timeoutlen = 200 -- time to wait for a mapped sequence to complete (in milliseconds)
-- opt.title = true -- set the title of window to the value of the titlestring
-- opt.updatetime = 300 -- faster completion
-- opt.writebackup = false -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited
-- opt.expandtab = true -- convert tabs to spaces
opt.shiftwidth = 4 -- the number of spaces inserted for each indentation
opt.tabstop = 4 -- insert 4 spaces for a tab

opt.cursorline = true -- highlight the current line
opt.number = true
opt.relativenumber = true 
-- opt.signcolumn = "yes" -- always show the sign column, otherwise it would shift the text each time
opt.wrap = false -- display lines as one long line